server:
  port: 2001
spring:
  application:
    name: shop-provider
  profiles:
    active: @profile.env@

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
  instance:
    instance-id: shop-provider2001 # 解决在eureka页面上显示主机名的问题
    prefer-ip-address: true # 解决在eureka页面上不显示ip问题