spring:
  application:
    name: eureka-server
  profiles:
    active: dev
server:
  port: 6060
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
    appname: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 # 定义服务续约任务（心跳）的调用间隔，单位：秒
    lease-expiration-duration-in-seconds: 10 #定义服务失效的时间，单位：秒
  client:
    serviceUrl: # Eureka服务器的连接，默认为http：//XXXX：X/eureka/,但是如果采用DNS方式获取服务地址，则不需要配置此设置Eureka服务器的连接
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false # 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    register-with-eureka: false # 表示是否将自己注册到Eureka Server，默认为true。由于当前这个应用就是Eureka Server，故而设为false
  server:
    enable-self-preservation: false # 自我保护模式，当出现出现网络分区、eureka在短时间内丢失过多客户端时，会进入自我保护模式，即一个服务长时间没有发送心跳，eureka也不会将其删除，默认为true
    eviction-interval-timer-in-ms: 4000 # 过期实例应该启动并运行的时间间隔，单位为毫秒，默认为60 * 1000
