spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xierenjuan/spring-cloud.git
          search-paths: configdir # 搜索路径
          username: xierenjun
          password: longyao88
  application:
    name: config-server
  profiles:
    active: @profile.env@
server:
  port: 6064
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/