spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xierenjuan/spring-cloud.git
          search-paths: configdir # 搜索路径
          username: xierenjun
          password: longyao88
    bus:
      enabled: true #是否启用springcloud config bus
      trace:
        enabled: true # 开启跟踪总线事件
  application:
    name: config-server
  profiles:
    active: dev
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.0.193
    port: 5672
#SpringCloud暴露接口，暴露/bus/refresh接口
management:
  endpoints:
    web:
      exposure:
        include: refresh
server:
  port: 6064
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/
  instance:
    instance-id: config-server6064 # 解决在eureka页面上显示主机名的问题，就是实例名；如果启动多个实例，名字配置成不一样的
    prefer-ip-address: true # 解决在eureka页面上不显示ip问题